### ISSUE TITLE
WHMCS 7.6.1 系统计划任务报错

### ISSUE THREAD

**Issue by 5high** [Zzm317/V2raySocks#12]
Error: Call to a member function select_db() on null in /var/www/html/modules/servers/V2raySocks/hooks.php:130
Stack trace:
#0 /var/www/html/modules/servers/V2raySocks/hooks.php(29): V2RaySocks_CalcBandReset(Array, Array, Array)
#1 /var/www/html/includes/hookfunctions.php(0): WHMCS\Utility\SafeInclude::{closure}(Array)
#2 /var/www/html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): run_hook('AfterCronJob', Array)
#3 /var/www/html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->tearDown()
#4 /var/www/html/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#5 /var/www/html/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#8 /var/www/html/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#9 {main}

**Comment by 5high** [comment]
$query3 = \WHMCS\Database\Capsule::table('tblservers')->where('type', 'V2raySocks')->get();

hooks里上面这个查询结果为空造成了后面的错误。其实数据库里是有一条记录的，但是不知道为何这个查询没有返回结果，所以造成了问题。

**Comment by Zzm317** [comment]
建议检查服务器配置是不是正常的选择了v2raysocks插件

**Comment by 5high** [comment]
选择和设置都是正常，我索性重装Whmcs，现在好了。
